### ISSUE TITLE
ECS

### ISSUE THREAD

**Issue by MiMoer** [ProwlEngine/Prowl#140]
Why not use ECS architecture？

[https://github.com/genaray/Arch](url)

**Comment by michaelsakharov** [comment]
My primary goal is to create something that feels familiar to Unity devs. 
Switching to ECS would be a pretty big departure from that.
I also personally find GameObjects more intuitive and easier to work with, It's a simpler concept to grasp, especially for newcomers.
Now, I know ECS can offer some performance benefits, but we can achieve similar optimizations within the GameObject system.
For instance, using "Manager" components for high-performance scenarios (like particle systems) can give us comparable results without overhauling everything.
Effectively allowing you to selectively implement ECS if you absolutely need it.
But using ECS for everything, on every project even those super simple 2d ones? That seems like overkill to me.

For most projects, I find working with GameObjects is just faster and easier to debug. 
It's a tried-and-true system that can scale well from small projects to big ones.
There's also the whole ecosystem to consider. 
Sticking closer to Unity's original setup means better compatibility with existing tools and workflows. 
Plus, it's what most Unity devs are used to, which I hope will make Prowl more attractive to potential contributors.
I just think it's better as a tool in our toolkit rather than the entire toolbox.

Despite all this I have sorta left the door open a little, Prowl is very simple and the conversion from GameObject to ECS isn't as huge a task as it sounds.
If in the future my mind changes on the topic, switching should be possible.

**Comment by PaperPrototype** [comment]
> Why not use ECS architecture？
> 
> [https://github.com/genaray/Arch](url)

@MiMoer I would say that if you want Prowl to use github.com/genaray/Arch then all you have to do is add it! :P nothing stopping you from making a fork of the engine. This is something I'd like to try as well

**Comment by PaperPrototype** [comment]
Hmm, I wonder how hard hard it would be to make a live Immediate Mode Table View of all data being stored in Arch ECS... That could be interesting. Might give this a try sometime

**Comment by michaelsakharov** [comment]
Gonna close this as I don't see Prowl switching to ECS anytime soon if at all ever.
